### ISSUE TITLE
FEATURE: Localization Guidelines

### ISSUE THREAD

**Issue by iamjessklein** [wikimedia/WikimediaUI-Style-Guide#146]
Story: As a UX designer, I want to clearly understand how to practically implement “localizable” design.

Possible solutions: Either connecting this to every single section or add to one category (This is for Everyone).

Opportunity: right now this content is sprinkled throughout the guide on a very high level, however, if it was consolidated it would provide creators with a chance to deep dive into complex questions around localization.

**Comment by Volker-E** [comment]
Contents that could live in such page:
- script specifics
- icon universality
- LTR/RTL languages, bidirectionality
- TTB/[BTT](https://www.quora.com/Are-there-languages-which-write-from-bottom-to-top)  languages design provisions if we want to show-off as very smart
- localization in layouts (minimalistic vs condensed?)
- …?

**Comment by In1quity** [comment]
I think some information about _fixed size blocks_ with text, which needs to be localized, and about problems associated with it will be really useful.

**Comment by Volker-E** [comment]
@In1quity That's a good point, but we first have to make clear, that fixed size blocks are the anti-pattern for internationalization, for scripts outside of the product peoples' languages behind the original design. 
One step further could be how to deal with it, if there's no other way around. We already feature some advice on this at [“Dynamic text” section](https://design.wikimedia.org/style-guide/visual-style_typography.html#readability) with “Readability” of our Style Guide.

**Comment by pamela-drouin** [comment]
Per [this ticket](https://phabricator.wikimedia.org/T221109), I'd like to know how to handle the following:

1. How should the overall UI elements (Captions and Statements panels) look when oriented in RTL languages?
2. Within a given panel, how do we handle situations when both LTR and RTL languages are present?

**Comment by Volker-E** [comment]
@pamela-drouin I've tried to summarize a general approach on the ticket, awaiting feedback from RTL native speakers, which will then inform the further documentation here.

**Comment by Volker-E** [comment]
We've gone a more contextual way in the Style Guide to make it universally applicable. With the notes in the different sections similar to icon guidelines mentioning RTL considerations or [Typography article](https://design.wikimedia.org/style-guide/visual-style_typography.html) note
<img width="797" alt="image" src="https://user-images.githubusercontent.com/619536/123797446-09bf6200-d89b-11eb-9c75-baa428f02b75.png">
I'm gonna close this task. Please be assured that the work continues with further inputs at https://phabricator.wikimedia.org/T282679.
