### ISSUE TITLE
Move resources to a different folder and use submodules

### ISSUE THREAD

**Issue by viztor** [wikimedia/WikimediaUI-Style-Guide#232]
resources contains too many binaries files and it's better if we can minimize the size this folder to improve DX

**Comment by Dishebh** [comment]
If it is still up for grabs, can I take it?

**Comment by Volker-E** [comment]
Hi @Dishebh, thanks for your interest.

@Ladsgroup and myself were chatting about this issue today, and, given different angles to the problem, submodules don't seem to be the right approach here.
His recommendation were `git lfs`.

**Comment by Dishebh** [comment]
@Volker-E so we now don't have to worry about shifting those huge files, right? Instead, we will push and commit cloned changes using `git lfs`, and update the instructions accordingly in the readme file to let others know...?

**Comment by Volker-E** [comment]
@Dishebh Exactly, that should be the outcome aimed for. Captured in https://phabricator.wikimedia.org/T235013
@Ladsgroup has offered his help here given his expertise.

**Comment by Dishebh** [comment]
Oh great! And if it is not assigned to anyone yet, can I take up the issue? Also, is there a way I can contact you with if there is any query, or shall I ping you here only ? @Volker-E

**Comment by Volker-E** [comment]
@Dishebh GitHub is the simplest way to put new requests or provide bug feedback for Wikimedia's Design Style Guide. If you feel interested to more Wikimedia projects than Style Guide https://www.mediawiki.org/wiki/How_to_become_a_MediaWiki_hacker would be a good starting point.

**Comment by Volker-E** [comment]
Fixed by #245.

**Comment by viztor** [comment]
> Fixed by #245.

I'm not sure if this is really done. Moving the files to lfs is great. But since we already have those binaries in our previous commit. To reduce bundle size we will have to rewrite history with lfs

**Comment by Volker-E** [comment]
@viztor You're right, we have to reopen this issue due to technical limitations in the last step involved on our Wikimedia infrastructure. https://phabricator.wikimedia.org/T235013 is still the reference point.

**Comment by rinkydevi** [comment]
I can contribute in this issue,how can i proceed?

**Comment by danisztls** [comment]
Just to summarize the Phabricatoir discussion. This project is migrating to Figma and a new repo which will not contain large binaries.

**Comment by rhm856591** [comment]
I want work on this issue please assign me

**Comment by rhm856591** [comment]
I want work on this issue please assign me

**Comment by Volker-E** [comment]
[Codex, as design system for Wikimedia](https://doc.wikimedia.org/codex/latest/), has become the designated successor of the Design Style Guide and doesn't feature large files anymore. Therefore closing.
