### ISSUE TITLE
Move icons into its own repo

### ISSUE THREAD

**Issue by viztor** [wikimedia/WikimediaUI-Style-Guide#233]
icons should better stay organized in its own repo and could later be made available as a icon-font on npm

**Comment by Volker-E** [comment]
@viztor What ability or functionality is not fulfilled in the current way, icons are integrated into the Design Style Guide? What are you missing?

Also, be aware that we deliberately chose not to [officially support icon fonts any longer](https://phabricator.wikimedia.org/T154957), due to a number of technical shortcomings, stated in corresponding task.

**Comment by viztor** [comment]
> @viztor What ability or functionality is not fulfilled in the current way, icons are integrated into the Design Style Guide? What are you missing?
> 
> Also, be aware that we deliberately chose not to [officially support icon fonts any longer](https://phabricator.wikimedia.org/T154957), due to a number of technical shortcomings, stated in corresponding task.

This repo contains large binary files which made it quite difficult to maintain. Support for icons doesn't discontinue with the discontinuation of icon fonts I presume. In today's scenario, if I am to use any of those icons, I either download them separately or clone the entire repository which is completely unnecessary and takes up huge amount of space. If I am ever to use those icons in my project, the ideal way would be to use a git submodule, so I can keep it up-to-date with the latest version. Separate those icons from this repo would make it a lot easier to use them.

**Comment by danisztls** [comment]
@Volker-E Were SVG sprites tried? I had positive experiences with [svg-sprite](https://www.npmjs.com/package/svg-sprite).

I agree with @viztor, a full clone takes up 600MB of space or 129MB if shallow.

**Comment by Volker-E** [comment]
[Codex, as design system for Wikimedia](https://doc.wikimedia.org/codex/latest/), has become the designated successor of the Design Style Guide. Codex monorepo also features a [package dedicated to icons](https://www.npmjs.com/package/@wikimedia/codex-icons) where we're discussing integration of SVG source and dist files, where it now features Vue 3 Less mixins for each icon of our collection. Therefore closing.
