### ISSUE TITLE
FEATURE: Implement usability guidelines

### ISSUE THREAD

**Issue by jdittrich** [wikimedia/WikimediaUI-Style-Guide#32]
**Story:** As a UX designer, I want to make sure that features of Wikimedia Projects adhere to basic usability principles, like visibility, feedback, UI standards etc . 

**Possible solution:** Provide a section on Usability for Wikimedia Projects. A classic example are the Macintosh UI guidelines, which have a section on general UI principles. 

**Current problems:** 
* There are many usability principles, but they don't give a sense of ownership in Wikimedia projects.

**Comment by jdittrich** [comment]
Naturally, there are a lot of resources out there on usability – so why write them here? 

* having rules of usability easily accessible (and not behind a google search with a gazillion of hits)
* "The Styleguide" is a thing that people hopefully refer to in the future and which my become a source that designers, developers and product managers trust (with all its content). It may carry weight if one says: "The styleguide says, functions should have a visual representation [=visibility/affordance/signifiers]" (because it is in the styleguide). But if I say "Jacob Nielsen suggests…" that person is unknown to non-usability people and the will be "so what – some person says that?!"

**Comment by jdittrich** [comment]
@Volker-E @pauginer: I started to write at [visual-style_usability.html](https://github.com/jdittrich/WikimediaUI-Style-Guide/blob/usabilityguidelines/visual-style_usability.html)

**Comment by jdittrich** [comment]
I updated [usability](https://github.com/jdittrich/WikimediaUI-Style-Guide/blob/usabilityguidelines/visual-style_usability.html) and would like to add some examples. I saw that currently, the assets are exported SVGs from sketch. Shall I add my examples as image or do you want to add them via export from sketch, too. If you prefer the latter, shall I send you what I suggest as examples? ( @Incabell)

**Comment by Volker-E** [comment]
As meta notice, do we believe that it needs to be a distinct section of the style guide or wouldn't it be better to have (as it's currently structured already with accessibility) the topics accessibility and usability inherent to the other sections? Our style guide from our own rough plan is targeting making those topics so clear and strongly indicated, that an usability section would be at best a repetition of contents to be found elsewhere in it.

**Comment by Volker-E** [comment]
@jdittrich To your last question, it would be best to provide images as SVGs and we would in a next PR put them into the Sketch file for further export in 1x and 2x PNGs and SVGs.

**Comment by jdittrich** [comment]
> Our style guide – from our own rough planning – aim is to 
> make those topics so clear and strongly indicated

It is hard to answer. In the current version of the [styleguide](https://wikimedia.github.io/WikimediaUI-Style-Guide/) I found it hard to integrate; The usability section focuses on behavior, so it did not fit at "visual" well, and the "design principles" were too high-level. In future versions, I can imagine this to change, but for the current one I found it difficult to integrate.

**Comment by jdittrich** [comment]
>  it would be best to provide images as SVGs

Exactly this was my problem – I do not have the UI-elements as SVGs; nor would we have a way to easily create real looking examples from them (aka we don't use macs, thus sadly no Sketch).

**Comment by Walter0807** [comment]
How can I use the design elements in my website which is based on Mediawiki?

**Comment by Volker-E** [comment]
@Walter0807 There are a few different ways, what exactly would you like to use? Also I'd propose to switch this conversation to IRC #wikimedia-design is a good place to talk to me: Volker_E

**Comment by Walter0807** [comment]
@Volker-E I didn't find a specific guide of applying it to Mediawiki, I'm wondering if there is a way to pack the design and make a skin for Mediawiki? Thx!

**Comment by Volker-E** [comment]
@jdittrich From your [latest commit](https://github.com/jdittrich/WikimediaUI-Style-Guide/blob/usabilityguidelines/visual-style_usability.html) following topics were added to the “usability” page proposal:
- Adhere to standards and be consistent
- Show how one [user] can interact with an widget ~ provide interaction assistance
- Prevent Errors and alliviate them
- Care for keyboard usage

How would those play together? While I do understand every single one, I'm not yet sure about the stringent connection between those underneath the umbrella term.
Keyboard usage falls also under accessibility, consistency is one of our stated design principles.
Preventing errors is a very specific interaction pattern.

Do you have examples from other guidelines that are reflecting “usability” very well? I couldn't refer to it from the Human Interface Guidelines, neither from [macOS](https://developer.apple.com/design/human-interface-guidelines/macos/user-interaction/keyboard/) nor iOS…

**Comment by jdittrich** [comment]
> I'm not yet sure about the stringent  connection between those underneath the umbrella term.

With "stringent  connection" do you mean “something which explains that is should be exactly these?” 

In which case I need to say: There is none. It is what I find useful to consider – but there could be one, or some other ones… (The only case I know in which such a list was determined empirically, would be  the Nielsen/Moelich heuristics)

> consistency is one of our stated design principles.
It is, indeed, though in my usability suggestions as well as in the current form it needs some examples and explanations to be useful. It could be on a separate usability page or on a sub-page for that principle. 

> Preventing errors is a very specific interaction pattern

It is one of the 10 Nielsen heuristics, so I think it is not that unusual. It might have been included in particular because I stumbled upon some problems (probably in Wikidata) where the system does tell the users after the fact that something is wrong, if at all. 

> Do you have examples from other guidelines that are reflecting “usability” very well?

The classic '87 "Macintosh Human Interface Guidelines" would be my gold standard for usability focused guidelines. 

The current generation of guidelines (e.g. [elementary’s](https://elementary.io/docs/human-interface-guidelines#human-interface-guidelines)) seems to focus more on describing widgets, their use and typical combinations and use cases, which has the advantage that it is easier to apply in a template-y way. This, however, assumes a consistent environment, which might be the case for visual editor but not for any slow change done in other parts of the products where the context is very heterogeneous and \[buttons\] are made of brackets.

**Comment by Volker-E** [comment]
[Codex, as design system for Wikimedia](https://doc.wikimedia.org/codex/latest/), has become the designated successor of the Design Style Guide and features various usability related guidelines. Therefore closing.
