### ISSUE TITLE
Indicate Draggability/Droppability

### ISSUE THREAD

**Issue by jdittrich** [wikimedia/WikimediaUI-Style-Guide#33]
**Story:** As a designer I may need to provide reorderable lists or sliders as interface elements
**Problem:**  Nor components nor styleguide give help on how to provide indication for draggability, and possible drop zones.

**Comment by Volker-E** [comment]
@jdittrich This will be part of the “Components” section. In the meantime please refer to the OOUI demos with [SelectFileWidgets drop target](https://doc.wikimedia.org/oojs-ui/master/demos/?page=widgets&theme=wikimediaui&direction=ltr&platform=desktop#SelectFileWidget-with-drop-target) for a droppability area and [DraggableGroupWidget with handles](https://doc.wikimedia.org/oojs-ui/master/demos/?page=widgets&theme=wikimediaui&direction=ltr&platform=desktop#DraggableGroupWidget-with-handles-vertical) for draggable indicators.

**Comment by Swayamsvk** [comment]
Can I work on this?

**Comment by Volker-E** [comment]
Please note that we've deprecated the Design Style Guide in favor of it's successor [Codex, Design System for Wikimedia](https://doc.wikimedia.org/codex/latest/). 
There's a task for continuation of the original question stated here: https://phabricator.wikimedia.org/T356644
