### ISSUE TITLE
Preferred mode of contributing

### ISSUE THREAD

**Issue by jdittrich** [wikimedia/WikimediaUI-Style-Guide#34]
**Story:** I would like to contribute e.g. with a section on usability principles
**Question:** What is your preferred mode of contribution? 
* Do you want to  make me a member so I can push directly to a branch, which someone else can merge?
* Shall I fork to my own repo and make pull requests? (Which provides an additional level of separation, but imho makes updating and pushing harder for contributors, particularly those with less git experience aka designers)

**Comment by jdittrich** [comment]
According to @pauginer, @Volker-E is the (only) direct contributor to the repo; contributions are made by fork, branch, pull request.

**Comment by Volker-E** [comment]
Adding to this, although I'm admin (together with @prtksxna and @juliengirault on that repo – and basically all Wikimedia organization admins), we're all fully committed to the same Gerrit conventions here, which means [no self-merging besides very trivial changes](https://www.mediawiki.org/wiki/Gerrit/%2B2).
It makes sense to follow the general GitHub approach on 
1. forking it to your own repo, 
2. merge in there and 
3. make a pull request to the main repo.

**Comment by Volker-E** [comment]
@jdittrich Also captured in https://github.com/wikimedia/WikimediaUI-Style-Guide/blob/master/CONTRIBUTING.md
