### ISSUE TITLE
Load Resource 404 Error

### ISSUE THREAD

**Issue by popoolatopzy** [wikimedia/WikimediaUI-Style-Guide#351]
The resource `fontfaceobserver.standalone.js` file added at the web page https://design.wikimedia.org/style-guide/components/file-inputs.html responded with a status of **404**

**Comment by Volker-E** [comment]
Thanks @popoolatopzy, I was able to reproduce this issue once in Chrome, but not repeatedly. Do you have any details on how to persistently reproduce it?

**Comment by popoolatopzy** [comment]
The resource  ` fontfaceobserver.standalone.js` file added at the web page is not linked properly. 

https://design.wikimedia.org/style-guide/components/js/vendor/fontfaceobserver/fontfaceobserver.standalone.js is used instead of 
https://design.wikimedia.org/style-guide/js/vendor/fontfaceobserver/fontfaceobserver.standalone.js

**Comment by olawanlejoel** [comment]
That's true!

**Comment by neelansh15** [comment]
@Volker-E This problem is present **all** the other pages in the components section, in the form of erroneous GET requests returning 404. I will see if I can do something about this.

**Comment by Volker-E** [comment]
@neelansh15 Please do so, patches are welcome!

**Comment by olawanlejoel** [comment]
@Volker-E was @neelansh15  able to fix this? If no, I could fix it if I get permission to do so.

**Comment by neelansh15** [comment]
@olawanlejoel I didn't post my solution here for lack of a better approach. You are free to come up with a solution :)

**Comment by olawanlejoel** [comment]
@neelansh15 , I would work on it.

**Comment by Volker-E** [comment]
@olawanlejoel Please go ahead!

**Comment by Volker-E** [comment]
Thanks @olawanlejoel for your patch!

**Comment by olawanlejoel** [comment]
Thanks @Volker-E
