### ISSUE TITLE
Alerts in Components

### ISSUE THREAD

**Issue by nitin10s** [wikimedia/WikimediaUI-Style-Guide#376]
**Description**
Alerts are an important part of a platform and user experience that helps maintain consistency. 

Currently, the Style Guide doesn't contain any components for Alerts. Alerts is a basic component that should be added.

**Comment by Volker-E** [comment]
Hi @nitin10s! Thanks for your inputs. 

Just to be fully clear, you're talking about a documentation in regards to standard [alert and notification dialogs as collected here](https://doc.wikimedia.org/oojs-ui/master/demos/?page=dialogs&theme=wikimediaui&direction=ltr&platform=desktop)?

**Comment by nitin10s** [comment]
Yes

**Comment by Princy06** [comment]
I would like to solve this issue @Volker-E @nitin10s . If you want to add any information or any details than I'll be thankful.

**Comment by Volker-E** [comment]
Fyi, related Phabricator (Wikimedia Foundation's bug tracker tool) task: https://phabricator.wikimedia.org/T266029

**Comment by Nightowl-8** [comment]
Hii there, I am interested to solve this issue. Can you assign this issue to me @nitin10s @Volker-E ?

**Comment by rhm856591** [comment]
I want work on this issue please assign me

**Comment by Volker-E** [comment]
Alerts in Dialogs are part of [Codex, as design system for Wikimedia](https://doc.wikimedia.org/codex/latest/), the improved and enhanced successor of the Design Style Guide. Therefore closing.
