### ISSUE TITLE
Specify "common meaning" for utility colors 

### ISSUE THREAD

**Issue by iamjessklein** [wikimedia/WikimediaUI-Style-Guide#397]
On the **[Color section](https://design.wikimedia.org/style-guide/visual-style_colors.html)** of the style guide, it states: 

`Utility colors are another type of accent color. Common meanings are associated with them. We use shades of red, green, and yellow as utility colors.`

However, we never say what the "common meanings" are that we associate with each color. This information would be helpful to have when determining the appropriate usage. Here's what I am thinking:

* Variants of red indicate errors in components, such as invalid text in a text field.
* Variants of green indicate successes in components.
* Variants of yellow indicate a non-disruptive warnings or alerts.

Is that accurate? Can we provide examples for each?

**Comment by SaiSan-WMDE** [comment]
Hi @iamjessklein! This is great. I think defining common meanings makes a lot of sense! Your approach is quite accurate, I would just add that:

- Variants of red are used to indicate errors in components, such as invalid input in a text field. They also represent destructive actions, such as delete or cancel.

About the examples, they should be easy to provide if needed.

**Comment by Volker-E** [comment]
@iamjessklein @SaiSan-WMDE I've added both your inputs and also provided an additional note on accessibility:
> <p>To indicate such meaning to visually impaired users, it's recommended to not only rely on a color, but use additionally clear action indicators like words and icons.</p>

**Comment by SaiSan-WMDE** [comment]
Looking good! Thanks, Volker 👍

**Comment by iamjessklein** [comment]
🏆
