### ISSUE TITLE
Add a link to the design team blog 

### ISSUE THREAD

**Issue by iamjessklein** [wikimedia/WikimediaUI-Style-Guide#414]
There should be an obvious link to the Wikimedia Design Blog somewhere on the website.

**Comment by dougmellon** [comment]
Would anyone mind if I take this for a first issue?

**Comment by Volker-E** [comment]
@dougmellon Please feel free to take it.
It makes sense to put it on the first page 'index.html' in the “Open to participate” section above “Follow Wikimedia Product Design team updates” list item.

**Comment by dougmellon** [comment]
Doing it right now. Thank you.

**Comment by Volker-E** [comment]
@dougmellon Great.
