### ISSUE TITLE
Menu icon in mobile view off alignment 

### ISSUE THREAD

**Issue by Nisarg-27** [wikimedia/WikimediaUI-Style-Guide#425]
In the mobile view of this website, the menu icon is not aligned properly with the logo. 

![problem](https://user-images.githubusercontent.com/77735347/105373131-59369d80-5c2c-11eb-9905-222f61e5a874.JPG)

The menu icon is slightly above the logo which does not look good. The top position should be increased slightly.

**Comment by Volker-E** [comment]
The reason for current position was to put top menu icon line best-possibly on [cap height line](https://en.wikipedia.org/wiki/Typeface_anatomy) of “Wikimedia”, not centered to both lines. 
<img width="324" alt="image" src="https://user-images.githubusercontent.com/619536/105607291-c6dce980-5d52-11eb-8587-8300578343f6.png">

If you are providing a patch, we could better evaluate your input.

**Comment by Nisarg-27** [comment]
I got that you're aiming to put the icon in line with "Wikimedia" but the system that I am using still shows the menu icon slightly above. 

The current position with top 1.2rem
![problem](https://user-images.githubusercontent.com/77735347/105624933-8745f880-5e4b-11eb-8672-52227f80e5a2.JPG)

The position I am proposing with top 1.5rem
![Solution](https://user-images.githubusercontent.com/77735347/105624947-ae9cc580-5e4b-11eb-8be1-3d7ccc26dcd4.JPG)

**Comment by Volker-E** [comment]
@Nisarg-27 I hope you're aware that the font is [dependent on the platform](https://github.com/wikimedia/WikimediaUI-Style-Guide/pull/99) one's browsing on and that [letter boxes are hard to come by](https://iamvdo.me/en/blog/css-font-metrics-line-height-and-vertical-align).
Without a clearly fleshed out and intensely wide tested plan, I don't think it's useful to put effort into this.

**Comment by Volker-E** [comment]
Closing this as is. Feel free to reopen when provide a patch set tested against our supported browser defined in  https://github.com/wikimedia/WikimediaUI-Style-Guide/blob/master/.browserslistrc
