### ISSUE TITLE
Increasing the width of color blocks 

### ISSUE THREAD

**Issue by Nisarg-27** [wikimedia/WikimediaUI-Style-Guide#426]
https://design.wikimedia.org/style-guide/visual-style_colors.html

In the mobile view of this page, the color blocks have a width of around 60% which leaves some white space on the right side of the page which does not look good

![problem 2](https://user-images.githubusercontent.com/77735347/105374351-9cddd700-5c2d-11eb-9804-2f5895a1864f.JPG)

If the width is increased to 100% it looks better than the existing size and covers the white space. 

![solution](https://user-images.githubusercontent.com/77735347/105374455-bc74ff80-5c2d-11eb-962b-8f471a1cd39a.JPG)

**Comment by Volker-E** [comment]
Hi @Nisarg-27, thanks for your reports!

Having the colors provided as block instead is an aesthetical _choice_, but full-width rectangular doesn't necessarily translate to “better” in our evaluation. For portrait mode for example it's advantageous to have two colors side-by-side.

**Comment by Nisarg-27** [comment]
If having the colors side by side is an advantage we can decrease the width to 49.8% 

![Solution2](https://user-images.githubusercontent.com/77735347/105625120-f3752c00-5e4c-11eb-8aea-e7b7c6d50fb1.JPG)

**Comment by Adityachaturvedi2906** [comment]
Hi,
  can I contribute to this? please guide me further.

**Comment by Volker-E** [comment]
Not convinced to have them so squeezed together, just to go into two columns. It's breaking our approach to emphasize whitespace as a design instrument.
I could only see a path for mobile only breakpoint up to 414px with somewhat like 
<img width="443" alt="image" src="https://user-images.githubusercontent.com/619536/107290369-40472e00-6a1b-11eb-9d47-cc6b43355f87.png">

**Comment by ravikr126** [comment]
Hii I want to work on this .please assign me this issue.

**Comment by Volker-E** [comment]
@ravikr126 Please feel free to provide a patch or any open questions!
