### ISSUE TITLE
Text flowing off the page

### ISSUE THREAD

**Issue by awantika10** [wikimedia/WikimediaUI-Style-Guide#436]
This document https://design.wikimedia.org/style-guide/resources/WikimediaUI-components_overview.svg has **POPUP** variant text appears floating onto the next page and makes text run off the screen.
![wikimedia0](https://user-images.githubusercontent.com/71998138/107380469-e70ef580-6b13-11eb-9f5b-66360c9eec0c.PNG)

**Comment by Volker-E** [comment]
Thanks @awantika10 for your input! Change is merged and will be deployed this week.
