### ISSUE TITLE
Add more component design guidelines

### ISSUE THREAD

**Issue by Nisarg-27** [wikimedia/WikimediaUI-Style-Guide#440]
Wikimedia style guide gives us a pretty good understanding of basic designing but I think there is room for more components to be added. 

Given below is a list of components that we can consider adding: 
1. Carousel
2. Navigation Bar
3. Progress Bar
4. Pagination

These are just a few basic components that come to mind and there are many more. @Volker-E  please let me know your thoughts on this so that I can send you a draft of the content which I am thinking of adding.

**Comment by khubaibalam2000** [comment]
Adding more designing components will give it a perfect and concise look.

**Comment by Volker-E** [comment]
Please also see https://phabricator.wikimedia.org/T277047 for a full overview of components to be designed and implemented.

**Comment by Adityachaturvedi2906** [comment]
Hey! this issue seems interesting, can I work on this issue for MediaWiki Hackathon 2021?

**Comment by Volker-E** [comment]
@Adityachaturvedi2906 Basically we're more than happy for help! 

What I've said above, [adding a component follows a process](https://github.com/wikimedia/WikimediaUI-Style-Guide/issues/440#issuecomment-793920247) and we (Wikimedia Design team) also got a few additions in the pipeline, **progress indicators** and **tabs**. 
Carousel is quite questionable if ever added to the style guide as usual Carousel implementation lacks certain usability principles and it's one of the least used/requested components in our environment.

**Comment by Adityachaturvedi2906** [comment]
Can you please help me with how can I start with this project?

**Comment by Volker-E** [comment]
@Adityachaturvedi2906 Have you ever worked on designing components for a design system in the past?
Did you make yourself comfortable with the Contributing guidelines?
Have you a specific component from the list above that you want to work on and made yourself a clear picture on how it's used currently in Wikimedia projects and what are the design requirements/constraints for it?

It might be a better choice to look through the existing components and look for things that are not clear to the public yet to start with a contribution…

**Comment by rinkydevi** [comment]
I can contribute in this issue, how can i proceed ?

**Comment by Nymphalys** [comment]
Thankyou @Volker-E to let me know from where to start,as I too wanted to contribute to this,I'll do the same as you suggested to @Adityachaturvedi2906

**Comment by rhm856591** [comment]
I want work on this issue please assign me

**Comment by Volker-E** [comment]
[Codex, as design system for Wikimedia](https://doc.wikimedia.org/codex/latest/), has become the designated successor of the Design Style Guide. We're featuring a [component roadmap at mediawiki.org](https://www.mediawiki.org/wiki/Codex/Planned_Components). Therefore closing.
