### ISSUE TITLE
Add "scroll to top" button in web page

### ISSUE THREAD

**Issue by Abhra303** [wikimedia/WikimediaUI-Style-Guide#443]
### Description
The Navbar of this web site is not sticky. As a result viewers have to scroll back again to the top to go to another page. For short articles this is fine. But for long articles it takes much time to scroll (specially for mobiles).

#### Screenshot

![ezgif com-gif-maker](https://user-images.githubusercontent.com/75240995/110099056-e1c96180-7dc6-11eb-9aa4-b3bb75ea8c10.gif)

So a "scroll to top" button can be added so that user can reach the nav bar more quickly and can go to the next page.

**Comment by Volker-E** [comment]
@jdlrobson How much insights do we have about such functionality on MobileFrontend?

**Comment by jdlrobson** [comment]
Usage on mobile beta of a jump to top was super low so we removed it. Many browsers have jump to top functionality built in (for example iOS allows you to do so by clicking on the address bar. In mobile we plan to use a sticky header or table of contents widget instead on the longer term. https://phabricator.wikimedia.org/T147026

**Comment by vishwjeet-singh** [comment]
@Abhra303 sir may i add scroll to top button at bottom left corner that appears when someone scrolls down a bit.

**Comment by Abhra303** [comment]
@vishwjeet-singh brother I am not from Wikimedia, 😅😅, just opened this issue..  

As jdlrobson said they are working to make the header sticky. So I think they will handle this issue

**Comment by Mihirkun** [comment]
Hiii there I want to contribute but I don't know how to contribute.

**Comment by prsmahajan** [comment]
Hi, I would like to work on this specific issue, can anyone tell me the issue within this problem and I will be started?

**Comment by userpavankumar** [comment]
Now, the website user can go to the top of the page with a single click.

If you scroll down the page and the page is so long and you want to go to the top of the page, you just click the arrow located in the bottom right corner.

## Pages before 'scroll to top' functionality.
![Screenshot (199)](https://user-images.githubusercontent.com/73659550/124425888-d98a2e80-dd86-11eb-84da-898281940bb1.png)


## Pages after 'scroll to top' functionality added.
### Here you will see the arrow at the bottom right corner
![Screenshot (200)_LI](https://user-images.githubusercontent.com/73659550/124426174-4c93a500-dd87-11eb-9e13-8eea9baa0f28.jpg)

**Comment by RoshanMhatre** [comment]
I will do it no time, please assign me this issue!

**Comment by Nightowl-8** [comment]
@Abhra303 sir, I want to contribute to this issue.

**Comment by TechDockDev** [comment]
@Abhra303 I wish to resolve this issue . please assign me this issue.

**Comment by Manogya46** [comment]
@Abhra303 I wish to resolve this issue . Please assign me this issue.

**Comment by Volker-E** [comment]
This functionality is not clearly argumented to be beneficial, see @jdlrobson comment about similar functionality on Wikipedia's MobileFrontend in comparison. It's currently not planned to be added to the Design Style Guide. In case the Wikimedia Design team makes it a priority, we'll re-open it again.
