### ISSUE TITLE
Add "dark mode" button in the website

### ISSUE THREAD

**Issue by 4kashyadav** [wikimedia/WikimediaUI-Style-Guide#448]

**Comment by Volker-E** [comment]
@4kashyadav Please provide a bit more context on what you want to achieve or have covered? Otherwise this issue won't be workable.

**Comment by saurabh853** [comment]
I want to contribute

**Comment by ashexy** [comment]
I want to work on this.
Can i contribute?

**Comment by Volker-E** [comment]
Hi all, please feel free to contribute. [Contributions are welcome](https://github.com/wikimedia/WikimediaUI-Style-Guide/blob/master/CONTRIBUTING.md) in Wikimedia Design Style Guide. 
First step would be to clarify the issue definition. What should be accomplished by this task and its code changes?

**Comment by AshishRajIITI** [comment]
Heyy @Volker-E, I suppose what @4kashyadav wanted to say is that the Wikimedia website presently doesn't have the dark mode feature. Since The idea behind dark mode is that it reduces the light emitted by device screens while maintaining the minimum color contrast ratios required for readability, and most of the modern websites contain this feature, adding this feature to the Wikimedia website will be a very good idea. The dark-mode button will help in toggling between light-mode and dark-mode as and when the user wants. 
This is what I realized after seeing the issue and heading towards the website.
I am new to open-source contribution and looking into details of whatever I can understand from the issues, so writing this clarification for the issues. I will be very grateful to contribute to this project. Thank you, sir:)

**Comment by Ashleyisreal** [comment]
Hi!
I am Utkarsh, a GSoC applicant and a 2nd year undergraduate Electronics and Communication student at Indian Institute of Information Technology Allahabad, India. I am really interested into designing stuff and creative thinking but I don't mind banging lines of code to build stuff. I am also a Frontend Developer.

If someone could guide me on how i can start contributing, it would be really helpful for me.
I am really exciting to learn new things and to work with you all.

Thanks and regards,
Utkarsh

**Comment by 4kashyadav** [comment]
I am adding the button named "D" , if we click on that then the dark mode will be activated. Dark mode is here to help with this, making the screen easier to see in low lighting such as in the night or early morning. It can be a lot easier on the eyes, causing less strain and is better in the long run. So can you assign me this because I want to contribute in this.
See some results - 
![Screenshot (476)](https://user-images.githubusercontent.com/78416508/112643821-c8b64c80-8e6a-11eb-8d22-01bafce5fc26.png)
![Screenshot (477)](https://user-images.githubusercontent.com/78416508/112643842-cce26a00-8e6a-11eb-88ce-c6fe8de60418.png)

**Comment by imranhadi01** [comment]
i wanna work on this issue. please assign this to me.

**Comment by Volker-E** [comment]
Thanks for the comments here @AshishRajIITI and following. 

I do think that there's a misunderstanding of how design decisions are achieved in Wikimedia Foundation. Yes, we're aware of a dark mode missing for Wikimedia projects in general, but there have been a number of things to be considered before coming up with a code implementation. 
Please see https://phabricator.wikimedia.org/T26070 or https://phabricator.wikimedia.org/T221425 for former discussions. 
It's not clear at the moment how the Wikimedia Foundation would enable such functionality on a project like Wikipedia and tame the maintenance burden in a resource-limited environment. 
Also please see an updated and further evolved implementation as user script which can found here: https://en.wikipedia.org/wiki/User:Volker_E._(WMF)/dark-mode

**Comment by himanshujasuja1040** [comment]
I Would really keen to contribute on this issue. I will put my best efforts to make it as beauttiful as I can .

**Comment by Volker-E** [comment]
@himanshujasuja1040 Have you read and understood my comment above?

**Comment by Sanyam17-beep** [comment]
hey I'm new to open source contribution I know html css and js  can anyone please guide how do i start

**Comment by dougmellon** [comment]
@Sanyam17-beep please reference the [comment](https://github.com/wikimedia/WikimediaUI-Style-Guide/issues/448#issuecomment-811106653) from @Volker-E above.

**Comment by alone-ant** [comment]
Hello I can use html,css and js to add this feature

**Comment by Ganaik2004** [comment]
i want to contribute to this project. please assign it to me.

**Comment by Triparno04** [comment]
I'm eager to contribute to implement dark mode feature to the website. Please provide guidance on how I can get started and contribute effectively.

**Comment by Yadnyesh-Dashpute** [comment]
Please Assigned Me a problem i have experienced in Html, Css and Js.

**Comment by Nitin-Singh-2002** [comment]
Assign this problem to me I will solve this problem with all my skills and experience in HTML, CSS, JS, React.

**Comment by Nandini99-git** [comment]
I would like to work on this, please assign me.

**Comment by draunger** [comment]
Assign me

**Comment by Volker-E** [comment]
[Codex, as design system for Wikimedia](https://doc.wikimedia.org/codex/latest/), has become the designated successor of the Design Style Guide and we're not further developing the contents of this repository. Therefore closing.
