### ISSUE TITLE
ADD follow section in footer!

### ISSUE THREAD

**Issue by 4kashyadav** [wikimedia/WikimediaUI-Style-Guide#452]
I will add a follow section in your footer in which I will add some buttons of Instagram, Twitter, Facebook, and so on so can you assign me this, please!
Like this:
![Screenshot (508)](https://user-images.githubusercontent.com/78416508/113910889-f4382000-97f6-11eb-85de-206f864fc9fa.png)

**Comment by 4kashyadav** [comment]
@Volker-E sir please assign this to me!! I want to contribute!

**Comment by imranhadi01** [comment]
i wanna work on this issue.

**Comment by Volker-E** [comment]
@4kashyadav @imranhadi01 Sorry, this is not in plan for the Wikimedia Design Style Guide. 
There are several issues with the approach:
- I don't even know how you ended up with Facebook or Instagram? Wikimedia Design doesn't use either.
- We already have linked GitHub and Twitter from the footer
- Using logos of other companies would need to have license or copyright notices mentioned.

We don't see an added value in these iconographic links and the problem statement on this task is insufficient to explain.
