### ISSUE TITLE
Transform build scripts from Grunt to npm based scripts

### ISSUE THREAD

**Issue by Volker-E** [wikimedia/WikimediaUI-Style-Guide#465]
As of current, we're basing our [build scripts on Grunt](https://github.com/wikimedia/WikimediaUI-Style-Guide/blob/master/Gruntfile.js). 
To reduce maintenance overhead, dependencies and be future-proof, we should move over to npm scripts.

**Comment by prsmahajan** [comment]
Hi, I want to work on this issue, can you suggest ways to get started?

**Comment by awantika10** [comment]
Hey @Volker-E, I wish to take up this issue. However, I am new to Grunt. Could you please give me an overview of how to go about converting Gruntfile to npm scripts?

**Comment by dougmellon** [comment]
@awantika10 I am busy right now but tonight or tomorrow I can walk you through this.

**Comment by dougmellon** [comment]
@Volker-E I'll take this and walk @awantika10 through the process.

**Comment by awantika10** [comment]
> @Volker-E I'll take this and walk @awantika10 through the process.

Thanks! Where do we start with?

**Comment by danisztls** [comment]
I'm hijacking this issue.

## Grunt and tooling context

*check [package.json](https://github.com/wikimedia/WikimediaUI-Style-Guide/blob/master/package.json) & [Gruntfile.js](https://github.com/wikimedia/WikimediaUI-Style-Guide/blob/master/Gruntfile.js)*

- [ ] JS Linting -> [ESlint](https://eslint.org/)
- [ ] JS Building -> [ESbuild](https://esbuild.github.io/)
- [ ] CSS Linting -> [Stylelint](https://stylelint.io/)
- [ ] CSS Postprocessing -> [PostCSS](https://postcss.org/)
- [x] Bitmap optimization -> [Squoosh](https://github.com/GoogleChromeLabs)
- [x] Vector optimization -> [svgo](https://github.com/svg/svgo)
- [ ] Watching -> ?

**Comment by Volker-E** [comment]
In #507 @danisztls proposed to replace soon-to-be deprecated Squoosh, which seems reasonable to me.

**Comment by rhm856591** [comment]
Hi, i am interested in this issue i want to contribute, can you give me suggestion that how to start?

**Comment by Volker-E** [comment]
[Codex, as design system for Wikimedia](https://doc.wikimedia.org/codex/latest/), has become the designated successor of the Design Style Guide and doesn't feature large files anymore. Therefore closing.
