### ISSUE TITLE
Consider dropping Squoosh

### ISSUE THREAD

**Issue by danisztls** [wikimedia/WikimediaUI-Style-Guide#507]
Squoosh will be deprecated by it's [author](https://github.com/GoogleChromeLabs/squoosh/pull/1266#issuecomment-1208149979) and support only up to Node v16 being  the sole blocker of an update from Node v12 to v18.

The project uses Squoosh to generate PNGs from SVGs. [sharp](https://www.npmjs.com/package/sharp) is a possible replacement.

**Comment by SerDIDG** [comment]
For the time being, we can add `NODE_OPTIONS=--no-experimental-fetch` to the package scripts, as in this commit:
https://github.com/argoproj/argo-workflows/commit/0b6e9417a1f72c713ddc5910d267530bd3c96563

**Comment by danisztls** [comment]
@SerDIDG That works but #508 replaces Squoosh with Sharp so a workaround isn't needed.

**Comment by arunimaChintu** [comment]
I want to get started. Can you guide me how to get started!

**Comment by ashvinichilbule** [comment]
I want to work on issue please assigned it to me

**Comment by Volker-E** [comment]
[Codex, as design system for Wikimedia](https://doc.wikimedia.org/codex/latest/), has become the designated successor of the Design Style Guide and doesn't feature large files anymore. Therefore closing.
